import "./globals.css";
import NavBar from "@/components/NavBar";

export const metadata = {
  title: "Todo App ",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div className="max-w-3xl mx-auto p-4">
          <NavBar></NavBar>
          <div className="mt-8">{children}</div>
        </div>
      </body>
    </html>
  );
}
